### ISSUE TITLE
🤡

### ISSUE THREAD

**Issue by billythegoat356** [Ramokprout/waspedent#1]
imagine etre fan de moi a ce point ptdrrr trouve toi une vie c trop

**Comment by LawlietRen** [comment]
Effectivement elle est là

**Comment by Ramokprout** [comment]
imagine vendre 30€ un grabber nul qui récup pas les mdp de firefox, avec une obfu nul, et prendre le seum au point de menacer de ban de ton vieux serveur discord les gens qui star mon repo mdrrrr la honte internationale le dev python
![image](https://user-images.githubusercontent.com/63268168/185736970-4887f456-4b1d-42b3-a3d6-f4a25171644d.png)
