### ISSUE TITLE
T'as peur?

### ISSUE THREAD

**Issue by billythegoat356** [Ramokprout/waspedent#3]
Pourquoi tu close l'issue?
Tu sais très bien qu'au fond de toi t'es qu'une merde.
Chaque fois que je sors un nouveau programme t'es toujours la a chercher des failles / le critiquer alors que tu fais pas mieux.

L'obfuscation est incroyable, assume le, tu veux juste rabaisser...

Et oui je te ban vu que tu fais que troll et casser les couilles (c'est la seule chose que tu sache faire dans ta vie).
Et après tu me parles de rageux alors que dès que je t'ai ban tu sors la source sur GitHub? 😂

Ridicule.
Trouve-toi une vie au lieu d'essayer de rabaisser les autres.

"Ramokprout chiasse" t'as 10 ans d'âge mental.

**Comment by Ramokprout** [comment]
oh oui billy j'ai trop peur de ton issue :(
#effrayé
ton plus sérieusement connard tu pollues ma boite mail si tu veux parler viens discord et cplc tocard
ton obfu protege rien (https://github.com/Bleu-No/Hyperion-Deobfuscate/blob/main/_help.py) dommaged
et oui je leak la source de ton programme a 30€ parce que vendre ça 30€ c'est une honte nationale

**Comment by Ramokprout** [comment]
avec tes majuscules et tes point la
nez
https://cdn.discordapp.com/attachments/1005557549438873692/1010292379774898337/unknown.png

**Comment by Ramokprout** [comment]
les issues github c'est pas fait pour régler ses comptes espèce d'abruti

**Comment by Ramokprout** [comment]
tu peux d'ores et déjà aller te faire foutre et refaire un obfuscateur python stp

**Comment by Ramokprout** [comment]
onon hyperion meilleur obfu du monde deob mais comment on va faire ahient :(:(:(::(:(:(:(::(:(:(::(:(::(
